### ISSUE TITLE
Publish a new version of the package

### ISSUE THREAD

**Issue by marcogrcr** [ljharb/promise-deferred#10]
The last version of the package [2.0.3][1] was created in [Jan 2020][2]. Since then, [13 commits][3] have been added, including an upgrade of the `promises` dependency from `7.x.x` to `8.x.x`. Can you publish a new version with these changes?

[1]: https://www.npmjs.com/package/promise-deferred/v/2.0.3
[2]: https://github.com/ljharb/promise-deferred/releases/tag/v2.0.3
[3]: https://github.com/ljharb/promise-deferred/compare/v2.0.3...main

**Comment by ljharb** [comment]
Hmm - in b50f4a8 i downgraded it to v2, but in c8226e5 (unreleased) i upgraded it again, claiming 729483b caused the break, but i didn't revert 729483b in any way.

Unfortunately that was 3 years ago, and I can't recall what was breaking - there's no open issues or anything. It might have been https://github.com/ljharb/promiseback/commit/61c686757c184d8d579bf51115b97f70b992b043 - in which case it'd be _technically_ still a breaking change but maybe not an actual one in practice.

I'll give it a shot :-)

**Comment by ljharb** [comment]
v2.0.4 is published.

Note that I'd suggest using https://npmjs.com/promise.withresolvers instead of this package, now that it's becoming a standard thing.

**Comment by marcogrcr** [comment]
Thank you so much! Does it make sense to deprecate the package in favor of `promise.withresolvers` in order to boost its visibility?

**Comment by ljharb** [comment]
potentially; promise-deferred works without a global Promise, but `promise.withresolvers` requires one. so, i might end up having to publish a v3 to do that.
