### ISSUE TITLE
Typescript index file

### ISSUE THREAD

**Issue by lygstate** [ljharb/promise-deferred#9]

**Comment by ljharb** [comment]
I’m not sure what this is for. This is not a typescript project, so typescript type definitions don’t belong here.

If you’d like types for this package, please see DefinitelyTyped.

**Comment by lygstate** [comment]
@ljharb npm i -S @types/promise-deferred doesn't exist.
You can inlcude the types file in promise-deferred directly

**Comment by ljharb** [comment]
It is a horrifically terrible idea to include TypeScript types directly in a non-TypeScript project.

If you'd like to see types for this package, please do submit a PR to add them as a new types package to DefinitelyTyped - I'd be happy to review them.

**Comment by lygstate** [comment]
@ljharb  lots of project doing that? didn't got the point that's horrifically

**Comment by ljharb** [comment]
- https://twitter.com/ljharb/status/1287770855691280384 (unnecessary deps)
 - https://twitter.com/__dfreeman/status/1268558650055983110 (the semver of your package can be affected by types as well as the actual code, and conflating the semver of two APIs into one is bad)
 - in a non-TS project, there would be nothing ensuring that the types and the implementation do not drift apart, which would also worsen the semver problem mentioned above
